FUNC LABEL 0
    MOV REG 0 VAL 1
    MOV REG 1 VAL 1
    CAL VAL 1
    CAL VAL 2
    CAL VAL 3
    CAL VAL 4
    CAL VAL 5
    CAL VAL 6
    CAL VAL 7
    PRINT REG 0
    RET
FUNC LABEL 1
    ADD REG 0 REG 1
    MOV REG 1 VAL 2
    RET
FUNC LABEL 2
    ADD REG 0 REG 1
    MOV REG 1 VAL 3
    RET
FUNC LABEL 3
    ADD REG 0 REG 1
    MOV REG 1 VAL 4
    RET
FUNC LABEL 4
    ADD REG 0 REG 1
    MOV REG 1 VAL 5
    RET
FUNC LABEL 5
    ADD REG 0 REG 1
    MOV REG 1 VAL 6
    RET
FUNC LABEL 6
    ADD REG 0 REG 1
    MOV REG 1 VAL 7
    RET
FUNC LABEL 7
    ADD REG 0 REG 1
    RET
