FUNC LABEL 0
    MOV STK A VAL 5
    REF REG 0 STK A
    CAL VAL 1
    PRINT STK A
    RET
FUNC LABEL 1
    MOV STK A REG 0
    REF PTR A STK A
    PRINT PTR A
    MOV STK B PTR A
    REF PTR B PTR A
    PRINT STK B
    RET
