FUNC LABEL 0
    MOV STK A VAL 0
    MOV STK B VAL 1
    MOV REG 0 STK A 
    CAL VAL 1
    PRINT REG 0
    MOV REG 0 STK B
    CAL VAL 1
    PRINT REG 0
    RET
FUNC LABEL 1
    MOV REG 1 VAL 1
    MOV REG 2 VAL 2
    EQU REG 0
    ADD REG 7 REG 0
    ADD REG 7 REG 1
    ADD REG 7 REG 2
    ADD REG 0 REG 1	
    RET
    ADD REG 0 REG 2
    RET
