FUNC LABEL 0
    MOV STK A VAL 5
    MOV STK B VAL 6
    REF STK B STK A
    PRINT STK B
    REF REG 0 STK B
    CAL VAL 1
    PRINT STK B
    RET
FUNC LABEL 1
    MOV STK A REG 0
    REF STK B PTR A
    PRINT STK B
    REF REG 1 PTR A
    PRINT REG 1
    MOV PTR A VAL 7
    RET
